frr version 9.1.2_git
frr defaults traditional
hostname FRR-Router-2
no ipv6 forwarding
!
interface eth0
 ip address 10.0.0.6/30
exit
!
interface eth1
 ip address 10.0.0.9/30
exit
!
interface eth2
 ip address 10.2.0.1/28
exit
!
interface eth3
 ip address 192.168.99.2/28
exit
!
router ospf
 network 10.0.0.4/30 area 0
 network 10.0.0.8/30 area 0
 network 10.2.0.0/28 area 0
exit
!
